[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
path = "./ClashFX"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
defaultToKeys = false
additive = false
unstripped = false

[update.transform]
codePath = "./ClashFX"
localizablePath = "./ClashFX"
transformer = "foundation"
supportedLanguageEnumPath = "./ClashFX"
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "./ClashFX"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "./ClashFX"
duplicateKeys = true
emptyValues = true
